apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
    name: podinfo
    namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/jipara/install-calico-with-ansible
  ref:
    branch: main
