apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
    name: chartmuseum
    namespace: flux-system
spec:
  interval: 5m
  chart:
    spec:
      chart: calico-network-policy
      version: "2.14.2"
      sourceRef:
        kind: GitRepository
        name: podinfo
        namespace: flux-system
      interval: 1m
